name: flutter_clean_architecture
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #service locator 
  get_it: ^8.2.0

  #Bloc for state management 
  flutter_bloc: ^9.1.1

  #Value equality
  equatable: ^2.0.7

  #functional programming thingies 
  dartz: ^0.10.1

  #Remote API
  #open a socket a listen to the socket it doesn't check if device android or ios
  data_connection_checker_nulls: ^0.0.2
  connectivity_plus: ^7.0.0
  http: ^1.5.0

  #local cache
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.5.1
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg

